#!/bin/sh

# Set these paths appropriately

BIN="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/bin"
CMD="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/cmd"
LIB="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/greek-mwls.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/greek-abbreviations
PARFILE=${LIB}/greek.par

$TOKENIZER -a $ABBR_LIST $* |
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

