#!/bin/sh

# Set these paths appropriately

BIN="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/bin"
CMD="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/cmd"
LIB="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
