#!/bin/sh

# Set these paths appropriately

BIN="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/bin"
CMD="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/cmd"
LIB="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/finnish-abbreviations
PARFILE=${LIB}/finnish.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE

