#!/bin/sh

# Set these paths appropriately

BIN="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/bin"
CMD="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/cmd"
LIB="/mnt/c/AIDPFM/aidpfm-novel/nlp-packages-comparison/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek-beta.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

